#!/hint/sh

# Define additional functionality for pinentry. For example
#test -e /usr/lib/libgcr-base-3.so.1 && exec /usr/bin/pinentry-gnome3 "$@"
#test -e /usr/lib/libQt5Widgets.so.5 && exec /usr/bin/pinentry-qt "$@"

if [[ "$(command -v pinentry-curses)" ]]; then
    exec /usr/bin/pinentry-curses "$@"
elif [[ "$(command -v pinentry-tty)" ]]; then
    exec /usr/bin/pinentry-tty "$@"
elif [[ "$(command -v pinentry-gnome3)" ]]; then
    exec /usr/bin/pinentry-gnome3 "$@"
fi
