#!/bin/sh

# always use 'sudo' with the following commands
for command in cryptsetup mount umount poweroff reboot shutdown su ufw updatedb apk rc-service rc-update service ; do
    alias $command="sudo $command"
done; unset command

alias \
    cp="cp -iv" \
    g="git" \
    ls="ls -lah --color=auto --group-directories-first" \
    mkd="mkdir" \
    mkdir="mkdir -pv" \
    mv="mv -iv" \
    rm="rm -v" \
    tmux="tmux -u" \
    v="vim"
