#!/usr/bin/env bash

# The `command` array will contain any commands that should assume `sudo`
command=(
    "cryptsetup"
    "dmesg"
    "mount"
    "poweroff"
    "reboot"
    "shutdown"
    "su"
    "ufw"
    "umount"
    "updatedb"
)

# Aliases for all distros - should not require additional packages
alias \
    ccat="highlight --out-format=ansi" \
    chmod="chmod -v" \
    chown="chown -v" \
    cp="cp -iv" \
    diff="diff --color=auto" \
    e="$EDITOR" \
    grep="grep --color=auto" \
    ip="ip -color=auto" \
    ka="killall" \
    mkd="mkdir" \
    mkdir="mkdir -pv" \
    mv="mv -iv" \
    rm="rm -v" \
    sdn="shutdown -h now" \
    v="$EDITOR"

# Aliases for all distros - may require additional packages
alias \
    bc="bc -ql" \
    ffmpeg="ffmpeg -hide_banner" \
    g="git" \
    lf="lfub" \
    mount_nfs="mount -a -t nfs" \
    rsync="rsync -avuP" \
    tmux="tmux -u" \
    tree="tree -a" \
    trem="transmission-remote" \
    weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \
    YT="youtube-viewer" \
    yt="yt-dlp --embed-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ytt="yt --skip-download --write-thumbnail" \
    ytv="yt -f \"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best\"" \
    z="zathura"

# For systems with an `xinitrc` file
if [[ -f "$XINITRC" ]]; then
    alias startx="startx $XINITRC"
fi

# For systems with an `mbsync` file
if [[ -f "$MBSYNCRC" ]]; then
    alias mbsync="mbsync -c $MBSYNCRC"
fi

# `ls` is different on Alpine Linux
if ! [[ "$(grep "ID=.*alpine" /etc/os-release)" ]]; then
    alias ls="ls -lahN --color=auto --group-directories-first"
else
    alias ls="ls -lah --color=auto --group-directories-first"
fi

# If `bat` is `batcat`, alias `bat` to `batcat`
if [[ "$(command -v batcat)" ]]; then
    alias bat="batcat"
fi

# If neovim is installed, alias `vim` to `nvim`
if [[ "$(command -v nvim)" ]]; then
    alias \
        vim="nvim" \
        vimdiff="nvim -d"
fi

# If `virsh` is installed
if [[ "$(command -v virsh)" ]]; then
    command+=("virsh")
fi

# PACKAGE MANAGERS
if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc_pkg-mgr" ]]; then
    source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc_pkg-mgr"
fi

# SERVICE MANAGERS
if [[ "$(command -v sv)" ]]; then
    alias shutdown="poweroff"

    command+=("sv")
elif [[ "$(command -v systemctl)" ]]; then
    command+=("systemctl")
elif [[ "$(command -v rc-service)" ]]; then
    command+=(
        "rc-service"
        "rc-update"
        "service"
    )
fi

# Renew `$PATH`
alias renew-path="export PATH=\"$PATH\""

# Rocky Linux aliases
# Rocky 8 systems run older versions of `tmux`, so these aliases cover that
if [[ "$(grep "ID=.*rocky" /etc/os-release)" ]]; then
    alias \
        tmux-config="tmux source-file ~/.config/tmux/tmux.conf" \
        tmux-kill="tmux kill-session -t" \
        tmux-new="tmux new-session -c ~/ -ds"
fi

# If user is NOT the root user, alias all commands in the `command` array
if ! [[ "$(whoami)" == "root" ]]; then
    if [[ "$(command -v doas)" ]]; then
        root_cmd="doas"
    elif [[ "$(command -v sudo)" ]]; then
        root_cmd="sudo"
    fi

    if [[ "$root_cmd" ]]; then
        for c in "${command[@]}" ; do
            alias $c="$root_cmd $c"
        done
    fi
fi

# Clean up
unset root_cmd
unset command

# Load any additional aliases
if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc_extra" ]]; then
    source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc_extra"
fi
