#!/usr/bin/env bash

# This script should handle the following situation:
# - if dwm, then `xinitrc` should have executed `dbus-launch ssh-agent dwm`:
#     - therefore, this script should exit, since `SSH_AGENT_PID` should be defined
#     - if ssh to dwm host, then this script should identify the `ssh-agent` process
# - if not dwm host, this script should start `ssh-agent` if it isn't running:
#     - if `ssh-agent` is running, then this script should identify the process

# Assert that `SSH_AGENT_PID` is not defined
if [[ "$SSH_AGENT_PID" ]]; then
    exit 0
fi

ssh_agent_lookup() {
    export SSH_AGENT_PID=$(pgrep -u $USER ssh-agent)
    export SSH_AUTH_SOCK=$(for f in ${HOME}/.ssh/agent/*; do if [[ -S $f ]]; then echo "$f"; break; fi; done 2> /dev/null)
}

# Look for `ssh-agent` process
ssh_agent_lookup

# If `SSH_AGENT_PID` or `SSH_AUTH_SOCK` are not defined, start `ssh-agent`
if [[ ! "$SSH_AGENT_PID" ]] || [[ ! "$SSH_AUTH_SOCK" ]] ; then
    (ssh-agent >| /dev/null)
    ssh_agent_lookup
fi

unset -f ssh_agent_lookup
